### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by 66246764** [sw32-seo/GTA#1]
Hello, thank you for your paper, but why do I follow your README.md, can't run the code? In Bash example / 05_ Best_ model_ test. sh error reporting:
![image](https://user-images.githubusercontent.com/54762477/163718807-8c239d35-8204-420f-9856-a8a3f7f8c925.png)

**Comment by sw32-seo** [comment]
Could you let me know which pytorch version you currently use?

**Comment by 66246764** [comment]
Thank you for your reply！
this is my version list
![image](https://user-images.githubusercontent.com/54762477/163753088-dcf2b699-ab13-49a3-867e-9d6192f1c6b6.png)

and after i debugged，i found that in this sentence
![image](https://user-images.githubusercontent.com/54762477/163753176-749e81d9-118c-4a63-a3d4-97cd2d30d6cb.png)
self.topk_ids is LongTensor, vocab_size is int,self._batch_index is LongTensor
but But when self.topk_ids is divided by vocab_size ，the result becomes FloatTensor，maybe that's the problem。

**Comment by sw32-seo** [comment]
I used torchtext==0.4.0
Could you try with that torchtext version?
or please follow requirements.txt and let me know the results.

**Comment by 66246764** [comment]
Sorry, I forgot to say. I noticed this and used the version of torchtext = = 0.4.0. This is the version list of my other environment:
![GK619 ~~5Q)S UE0$3)7GBS](https://user-images.githubusercontent.com/54762477/163757544-c5143670-6824-440f-8cb5-9fced66cad37.png)
![AK7CU8JPT15L8F~K) 0(UOD](https://user-images.githubusercontent.com/54762477/163757552-24d5a61d-a37d-4013-9719-9236e14d7be8.png)
But it still prompts the same error

**Comment by sw32-seo** [comment]
@66246764 According to below thread, torch.div cannot handle long type output anymore. 
[https://github.com/OpenNMT/OpenNMT-py/pull/1847](url)

I've just push fix for this change. Please pull my repo again and try.
If your problem is resolved, please let me know.

Thank you for your attention!

**Comment by 66246764** [comment]
it worked！
Thank you again for your help！

**Comment by sw32-seo** [comment]
You’re welcome :) Thx for contribution.
