### ISSUE TITLE
bash error

### ISSUE THREAD

**Issue by grepTurro** [sw32-seo/GTA#2]
Hello. I tried running the bash script Example/05_Best_model_test.sh but it shows this error 

**FileNotFoundError: [Errno 2] No such file or directory: 'experiments/USPTO-50k_no_rxn_Best_model/pred/output'**

I can see that there's no pred/output directory inside the best model USPTO-50k_no_rxn_Best_model downloaded from https://drive.google.com/drive/folders/1PlSXWR72TL8J56XrFPUBknMtuzL6o9Fo

Please let me know how to fix this. 

Thank you.

**Comment by sw32-seo** [comment]
Thank you for your attention @grepTurro !

Could you please put [these folders](https://drive.google.com/drive/folders/1Q2pZgfUwIricTL6c_I66HHW5ULOnLB1p?usp=sharing) (`USPTO-50k_no_rxn_Best_model` and `USPTO-50k_no_rxn`) into `experiments/` and then run bash script again?

This can be found in README.md 😄
